info:
  group-id: io.github.miguelarmasabt

quarkus:
  application:
    name: personal-finances-v1
  http:
    port: ${SERVER_PORT:8080}
    root-path: /poc/personal-finances/v1
    non-application-root-path: q
  log:
    category:
      "org.mongodb.driver.cluster":
        level: WARN
    console:
      enable: true
      json:
        pretty-print: false
  jackson:
    serialization-inclusion: non_null

  openapi:
    generator:
      server:
        use: apicurio
        spec: openapi.yaml
        input-base-dir: src/main/resources/openapi
        base-package: ${info.group-id}.expenses.rest.server
        use-reactive: false
        use-bean-validation: true
        skip-if-unchanged: false
        patcher:
          enabled: true
          request-bodies:
            saveExpense:
              resource: ExpensesResource
              target-class: ${info.group-id}.expenses.crud.dto.request.ExpenseSaveRequestDto
              parameter-name: data
            updateExpense:
              resource: ExpensesResource
              target-class: ${info.group-id}.expenses.crud.dto.request.ExpenseUpdateRequestDto
              parameter-name: data
            updateExpenseCategories:
              resource: ExpensesResource
              target-class: ${info.group-id}.expenses.categories.dto.request.ExpenseCategoryRequestDto
              parameter-name: data

  mongodb:
    connection-string: "mongodb+srv://miguelarmasabt:l21m01j16M01L13@cluster0.t2pidzg.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0&authSource=admin"
    database: personalManagement

  rest-client:
    logging:
      scope: request-response
      body-limit: 4096

    gmail:
      url: ${GMAIL_ENDPOINT}
      verify-host: false
      connect-timeout: 850
      read-timeout: 4500
      headers:
        Content-Type: application/json

    exchange-rate:
      url: ${EXCHANGE_RATE_ENDPOINT}
      verify-host: false
      connect-timeout: 850
      read-timeout: 4500
      headers:
        Content-Type: application/json

org:
  eclipse:
    microprofile:
      rest:
        client:
          propagateHeaders: trace-parent, caller-name, Authorization, request-date

configuration:

  features:
    gmail-messages:
      page-size: 10
      fields: 'messages/id,nextPageToken'
    gmail-message-content:
      format: full

    search-criteria:
      page-size: 20

    csv:
      imports:
        batch-size: 500
      exports:
        rows-per-chunk: 250

    bank-receipts:
      "BBVA_DEBIT_CARD":
        from: procesos@bbva.com.pe
        subject: "Has realizado un consumo con tu tarjeta BBVA"

      "BBVA_PLIN":
        from: procesos@bbva.com.pe
        subject: "Constancia de operación transferencia PLIN"

      "BBVA_PLIN_MERCHANT_QR":
        from: procesos@bbva.com.pe
        subject: "BBVA - Constancia de pago a comercios con QR"

      "BBVA_SERVICE_PAYMENT":
        from: procesos@bbva.com.pe
        subject: "BBVA - Constancia Pago de servicios"

      "IBK_PLIN":
        from: servicioalcliente@netinterbank.com.pe
        subject: "Constancia de Pago Plin"

#      "BCP_DEBIT_CARD":
#        from: notificaciones@notificacionesbcp.com.pe
#        subject: "Realizaste un consumo con tu Tarjeta de Débito BCP - Servicio de Notificaciones BCP"
#
#      "BCP_CREDIT_CARD":
#        from: notificaciones@notificacionesbcp.com.pe
#        subject: "Realizaste un consumo con tu Tarjeta de Crédito BCP - Servicio de Notificaciones BCP"
#
#      "BCP_YAPE_SERVICE":
#        from: noreply@yape.pe
#        subject: "Tu yapeo de servicio ha sido confirmado"
#
#      "BCP_YAPE":
#        from: notificaciones@yape.pe
#        subject: "Pago exitoso"